server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: @spring.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    default_property_inclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 192.168.118.17
  port: 6379
  password: root
  timeout: 2000
  #服务或应用名
  sysName: @artifactId@
  enable: true
  database: 5

info:
  name: @artifactId@
  discription: @my.discription@